=== MengaPierpaolo/teachus/teachus-test/src/test/resources/full.dtd
<!ELEMENT dataset (
    application_configuration*,
    person*,
    period*,
    booking*,
    teacher_attribute*)>

<!ELEMENT application_configuration EMPTY>
<!ATTLIST application_configuration
    name CDATA #REQUIRED
    version CDATA #REQUIRED
    value CDATA #IMPLIED
>

<!ELEMENT person EMPTY>
<!ATTLIST person
    id CDATA #REQUIRED
    person_type CDATA #REQUIRED
    version CDATA #REQUIRED
    name CDATA #IMPLIED
    username CDATA #REQUIRED
    password CDATA #IMPLIED
    email CDATA #IMPLIED
    phone_number CDATA #IMPLIED
    locale CDATA #IMPLIED
    theme CDATA #IMPLIED
    active CDATA #IMPLIED
    currency CDATA #IMPLIED
    teacher_id CDATA #IMPLIED
>

<!ELEMENT period EMPTY>
<!ATTLIST period
    id CDATA #REQUIRED
    version CDATA #REQUIRED
    name CDATA #IMPLIED
    begin_date CDATA #IMPLIED
    end_date CDATA #IMPLIED
    start_time CDATA #IMPLIED
    end_time CDATA #IMPLIED
    week_days CDATA #IMPLIED
    teacher_id CDATA #IMPLIED
    location CDATA #IMPLIED
    price CDATA #IMPLIED
    lesson_duration CDATA #REQUIRED
    interval_between_lesson_start CDATA #REQUIRED
    repeat_every_week CDATA #REQUIRED
    status CDATA #REQUIRED
>

<!ELEMENT booking EMPTY>
<!ATTLIST booking
    id CDATA #REQUIRED
    booking_type CDATA #REQUIRED
    version CDATA #REQUIRED
    active CDATA #IMPLIED
    period_id CDATA #IMPLIED
    date CDATA #IMPLIED
    create_date CDATA #IMPLIED
    update_date CDATA #IMPLIED
    teacher_id CDATA #IMPLIED
    pupil_id CDATA #IMPLIED
    notification_sent CDATA #IMPLIED
    paid CDATA #IMPLIED
>

<!ELEMENT teacher_attribute EMPTY>
<!ATTLIST teacher_attribute
    id CDATA #REQUIRED
    attribute CDATA #REQUIRED
    version CDATA #REQUIRED
    teacher_id CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== MengaPierpaolo/teachus/teachus-test/src/test/resources/full.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "src/test/resources/full.dtd">
<dataset>
  <application_configuration name="DEFAULT_TIMEZONE" version="0" value="Europe/Copenhagen"/>
  <application_configuration name="SERVER_URL" version="0" value="http://localhost:8080/"/>
  <application_configuration name="VERSION" version="0" value="1.2.3"/>
  <person id="1" person_type="ADMIN" version="0" name="Admin" username="admin" password="D033E22AE348AEB5660FC2140AEC35850C4DA997" email="teachus@billen.dk" active="1"/>
  <person id="2" person_type="TEACHER" version="0" name="Cathrine Sadolin" username="sadolin" password="2E56050EE8AF31E471C1288C45058554E7425599" email="cathrine.sadolin@billen.dk" locale="da_DK_singers" active="1" currency="kr"/>
  <person id="3" person_type="PUPIL" version="0" name="Anne Pedersen" username="anne" password="96657FD33D4351FB0EC777FD7064E03B0ADC3A35" email="anne.pedersen@billen.dk" active="1" teacher_id="2"/>
  <person id="4" person_type="PUPIL" version="0" name="Bent Jørgensen" username="bent" password="042EE58D65C9BFC6B8CC1DF7B1443801746E7FC2" email="bent.jorgensen@billen.dk" active="1" teacher_id="2"/>
  <person id="5" person_type="PUPIL" version="0" name="Christina Nielsen" username="christina" password="379784E41C3D7DCA2DF845D9A244769A066882F6" email="christina.nielsen@billen.dk" active="1" teacher_id="2"/>
  <person id="6" person_type="PUPIL" version="0" name="Dennis Jürgensen" username="dennis" password="7965A665163253A12F43312BF69D07012A113A2A" email="dennis.jurgensen@billen.dk" active="1" teacher_id="2"/>
  <person id="7" person_type="PUPIL" version="0" name="Eva Jensen" username="eva" password="031DB697456301F70B5DCF7E44BAD2C28D44755A" email="eva.jensen@billen.dk" active="1" teacher_id="2"/>
  <person id="8" person_type="PUPIL" version="0" name="Frederik Hansen" username="frederik" password="5EE7EEFB6634F9DE06952402BE37D30C97BC14D7" email="frederik.hansen@billen.dk" active="1" teacher_id="2"/>
  <person id="9" person_type="PUPIL" version="0" name="Grethe Sünk" username="grethe" password="09EED4D72F123434EC3B581C75D1BB919CD71087" email="grethe.sunk@billen.dk" active="1" teacher_id="2"/>
  <person id="10" person_type="PUPIL" version="0" name="Hans Madsen" username="hans" password="8800578B51F022C8D8ADB9606A8B3DB4FEDBDAC6" email="hans.madsen@billen.dk" active="1" teacher_id="2"/>
  <person id="11" person_type="PUPIL" version="0" name="Inge Holm" username="inge" password="70860DE7142914652C043A40F9EE76E96F2A8E22" email="inge.holm@billen.dk" active="1" teacher_id="2"/>
  <person id="12" person_type="PUPIL" version="0" name="Jørgen Noller" username="jorgen" password="ADC814BCDE78A4CE66F68F2F46769E6ABDD43145" email="jorgen.noller@billen.dk" active="1" teacher_id="2"/>
  <person id="13" person_type="PUPIL" version="0" name="Karen Finnsen" username="karen" password="55107E193E648A27778FA98736B2E8E24B3CD6E1" email="karen.finnsen@billen.dk" active="1" teacher_id="2"/>
  <person id="14" person_type="PUPIL" version="0" name="Lars Larsen" username="lars" password="3318DC5CE3E4FB7C28A0B841B6801C884E1D0896" email="lars.larsen@billen.dk" active="1" teacher_id="2"/>
  <person id="15" person_type="PUPIL" version="0" name="Maria Mogensen" username="maria" password="E21FC56C1A272B630E0D1439079D0598CF8B8329" email="maria.mogensen@billen.dk" active="1" teacher_id="2"/>
  <person id="16" person_type="PUPIL" version="0" name="Niels Funk" username="niels" password="A802A5730C0DA02A06106670CC12C7838C6E90DC" email="niels.funk@billen.dk" active="1" teacher_id="2"/>
  <person id="17" person_type="PUPIL" version="0" name="Olga Petersen" username="olga" password="D7A9089BF3F52040CEC8C19A2EFBE72F11AE1CAD" email="olga.petersen@billen.dk" active="1" teacher_id="2"/>
  <person id="18" person_type="PUPIL" version="0" name="Per Frimand" username="per" password="F47039FBB1F7F212938B642944291FC3B2E603C6" email="per.frimand@billen.dk" active="1" teacher_id="2"/>
  <person id="19" person_type="PUPIL" version="0" name="Rikke From" username="rikke" password="0061F119F5031D29B17EA095854FFB893E6AEF0B" email="rikke.from@billen.dk" active="1" teacher_id="2"/>
  <person id="20" person_type="PUPIL" version="0" name="Søren Jensen" username="soren" password="5A44A2B2FF2077806BFD50CA0791C72A2DAC44C0" email="soren.jensen@billen.dk" active="1" teacher_id="2"/>
  <person id="21" person_type="PUPIL" version="0" name="Trine Lund" username="trine" password="496AF612D23803604AA2682E8A413B9979B9CD79" email="trine.lund@billen.dk" active="1" teacher_id="2"/>
  <person id="22" person_type="PUPIL" version="0" name="Ulrik Andersen" username="ulrik" password="F31A70FFDAB4C8029E29DD9407EA3E3807D2A072" email="ulrik.andersen@billen.dk" active="1" teacher_id="2"/>
  <person id="23" person_type="PUPIL" version="0" name="Vera Pihl" username="vera" password="886FED01789257424228DC95FE3B5B319335AB6D" email="vera.pihl@billen.dk" active="1" teacher_id="2"/>
  <person id="24" person_type="PUPIL" version="0" name="Åge Hansen" username="aage" password="570D16DBFAFFFC9800AD051C950743DB18991B33" email="aage.hansen@billen.dk" active="1" teacher_id="2"/>
  <period id="1" version="0" name="Man/Ons/Fre" begin_date="2006-01-01" start_time="10:00:00" end_time="17:00:00" week_days="1,3,5" teacher_id="2" location="Copenhagen" price="400.0" lesson_duration="60" interval_between_lesson_start="60" repeat_every_week="1" status="FINAL"/>
  <period id="2" version="0" name="Tir/Tor" begin_date="2006-01-01" start_time="13:00:00" end_time="17:00:00" week_days="2,4" teacher_id="2" location="Copenhagen" price="400.0" lesson_duration="60" interval_between_lesson_start="60" repeat_every_week="1" status="FINAL"/>
  <period id="3" version="0" name="Weekend" begin_date="2006-01-01" start_time="14:00:00" end_time="18:00:00" week_days="6,7" teacher_id="2" location="Odense" price="800.0" lesson_duration="60" interval_between_lesson_start="60" repeat_every_week="1" status="FINAL"/>
  <booking id="1" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-01-02 14:00:00.0" create_date="2007-02-23 00:35:29.0" teacher_id="2" pupil_id="3" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="2" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-01-16 14:00:00.0" create_date="2007-02-23 00:35:33.0" teacher_id="2" pupil_id="3" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="3" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-01-30 14:00:00.0" create_date="2007-02-23 00:35:37.0" teacher_id="2" pupil_id="3" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="4" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-02-13 14:00:00.0" create_date="2007-02-23 00:35:42.0" teacher_id="2" pupil_id="3" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="5" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-02-27 14:00:00.0" create_date="2007-02-23 00:35:47.0" teacher_id="2" pupil_id="3" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="6" booking_type="PUPIL" version="0" active="1" period_id="2" date="2006-06-13 16:00:00.0" create_date="2007-02-23 00:36:17.0" teacher_id="2" pupil_id="4" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="7" booking_type="PUPIL" version="0" active="1" period_id="2" date="2006-06-15 16:00:00.0" create_date="2007-02-23 00:36:19.0" teacher_id="2" pupil_id="4" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="8" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-01-02 15:00:00.0" create_date="2007-02-23 00:36:39.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="9" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-02-06 15:00:00.0" create_date="2007-02-23 00:36:55.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="10" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-03-06 15:00:00.0" create_date="2007-02-23 00:37:10.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="11" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-04-03 15:00:00.0" create_date="2007-02-23 00:37:18.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="12" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-05-01 15:00:00.0" create_date="2007-02-23 00:37:26.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="13" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-06-05 15:00:00.0" create_date="2007-02-23 00:37:35.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="14" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-07-03 15:00:00.0" create_date="2007-02-23 00:37:42.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="15" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-08-07 15:00:00.0" create_date="2007-02-23 00:37:53.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="16" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-09-04 15:00:00.0" create_date="2007-02-23 00:38:02.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
  <booking id="17" booking_type="PUPIL" version="0" active="1" period_id="1" date="2006-10-02 15:00:00.0" create_date="2007-02-23 00:38:10.0" teacher_id="2" pupil_id="5" notification_sent="1" pupil_notification_sent="1" paid="1"/>
